### PR TITLE
Fixes synchronous operations.

### LINKED ISSUE #116: NullpointerException in Sync Request
I was trying to do a sync request with Wasp 1.3

I am getting the following NullPointerException
```

08-21 13:28:00.856    1698-1698/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.verisun.mobiett.debug, PID: 1698
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.orhanobut.wasp.VolleyNetworkStack$VolleyListener.onResponse(java.lang.Object)' on a null object reference
            at com.orhanobut.wasp.VolleyNetworkStack$VolleyRequest.deliverResponse(VolleyNetworkStack.java:191)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

The problem is (I think) that you are providing `null` as a listener into the request [here](https://github.com/orhanobut/wasp/blob/master/wasp/src/main/java/com/orhanobut/wasp/VolleyNetworkStack.java#L56) Instead `FutureRequest` object should be given as Success and Error Listeners. `FutureRequest` implements `com.android.volley.Response.Listener<T>` and `com.android.volley.Response.ErrorListener`

### PR DESCRIPTION
**Pull request by tasomaniac**
- T used in InternalCallback is wasp.Response class. Sync calls should return the given type of the request itself. I simply changed it to return Object. If you can suggest better alternative, that would be great.

- Future object is added to VolleyRequest. Either that or listener will be NonNull at a given time. RequestFuture's onResponse method must be called for blocking `future.get()` method to be finished.

Fixes #116

### CODE REVIEW

**Comment by tasomaniac** [comment]
BTW, I didn't touch RX counterpart of this. It maybe already working. I didn't try it. If the same problem is there as well, it needs to be fixed.

File: wasp/src/main/java/com/orhanobut/wasp/NetworkStack.java [hunk 1]
```diff
@@ -7,5 +7,5 @@
 
   <T> void invokeRequest(RequestCreator requestCreator, InternalCallback<T> waspCallback);
 
-  <T> T invokeRequest(RequestCreator requestCreator) throws Exception;
+  Object invokeRequest(RequestCreator requestCreator) throws Exception;
```
Comment (orhanobut) [inline wasp/src/main/java/com/orhanobut/wasp/NetworkStack.java]: That makes sense to have Object type here, now I'm thinking why we put T in the first place which doesn't make any sense.

Comment (tasomaniac) [inline wasp/src/main/java/com/orhanobut/wasp/NetworkStack.java]: T is always Response. Nothing else. 
I've updated the PR and replaced T with Response. Can you review it?

Comment (orhanobut) [inline wasp/src/main/java/com/orhanobut/wasp/NetworkStack.java]: I'm on it

File: wasp/src/main/java/com/orhanobut/wasp/VolleyNetworkStack.java [hunk 2]
```diff
@@ -159,22 +158,34 @@ public void onErrorResponse(VolleyError error) {
...
 
-    private final VolleyListener<T> listener;
+    private final VolleyListener<Response> listener;
+    private final RequestFuture<Object> future;
     private final String requestBody;
     private final String url;
     private final Type responseObjectType;
     private final RequestCreator waspRequest;
 
-    public VolleyRequest(int method, String url, RequestCreator request, VolleyListener<T> listener) {
```
Comment (orhanobut) [inline wasp/src/main/java/com/orhanobut/wasp/VolleyNetworkStack.java]: I think we should refactor this class, having 2 constructor which almost does the same job could be hard to maintain, I will suggest, let's change the constructor signature and adjust it to volley requirements. Request class only requires ErrorListener, Both VolleyListener and RequestuFuture already implement ErrorListener, passing them would be fine. so let's meet this requirement and handle response in the anonymous class, since sync and async handles it differently. 

VolleyRequest, we can remove the listener and requestfuture fields, no longer required, passing errorListener would be fine
```java

    //REMOVED private final VolleyListener<Response> listener;  
    //REMOVED private final RequestFuture<Object> future;

    public VolleyRequest(int method, String url, RequestCreator request,
                         com.android.volley.Response.ErrorListener errorListener) {
      super(method, url, errorListener);
      this.url = url;
      this.requestBody = request.getBody();
      this.responseObjectType = request.getMethodInfo().getResponseObjectType();
      this.waspRequest = request;
    }
```
request call and response handling for async
```java
    final VolleyListener<T> listener = new VolleyListener<>(waspCallback, url);
    Request<Response> request = new VolleyRequest<Response>(method, url, waspRequest, listener){
      @Override
      protected void deliverResponse(Response response) {
        super.deliverResponse(response);
        listener.onResponse(response);
      }
    };
```
for sync call
```java
    final RequestFuture<T> future = RequestFuture.newFuture();
    Request<Response> request = new VolleyRequest<Response>(
        getMethod(requestCreator.getMethod()),
        requestCreator.getUrl(),
        requestCreator,
        future
    ){
      @Override
      protected void deliverResponse(Response response) {
        super.deliverResponse(response);
        future.onResponse(response.getResponseObject());
      }
    };
```

File: wasp/src/main/java/com/orhanobut/wasp/VolleyNetworkStack.java [hunk 3]
```diff
@@ -187,8 +198,13 @@ public VolleyRequest(int method, String url, RequestCreator request, VolleyListe
     }
 
     @Override
-    protected void deliverResponse(T response) {
-      listener.onResponse(response);
+    protected void deliverResponse(Response response) {
```
Comment (orhanobut) [inline wasp/src/main/java/com/orhanobut/wasp/VolleyNetworkStack.java]: when we use the new signature, we can remove all response operations but leave the logging.

```java
protected void deliverResponse(Response response) {
   response.log();
}
```

**Comment by orhanobut** [comment]
Regarding to Rx, when the fix is done, Rx part will be fixed as well since it uses sync as request handling.

**Comment by tasomaniac** [comment]
Makes sense. I didn't want to touch the internal structure. I will update the PR asap.

**Comment by orhanobut** [comment]
Perfect, can you also squash the commits into one when you are done? We can merge and release a new version, thanks

**Comment by orhanobut** [comment]
@tasomaniac I'm waiting this PR to release a new version, since I also need this fix :)

**Comment by tasomaniac** [comment]
Suggested changes are made. 
Commits are squashed

**Comment by orhanobut** [comment]
:+1:
